This notebook explores examples of the extracted relationships with OpenIE.

The results of this notebook have been stored in csv and pickle files.
All code cells concerned with the generaiton of those file have been commented out. In case anyone wants to run this file, download the csv files from the google drive link into the folder called "files".

# Imports

In [1]:
import _pickle as pickle
import pandas as pd
from tqdm.notebook import tqdm
import os
from collections import defaultdict

In [2]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

# Load Triple Dict

Merged dictionary of all extracted relationship triples from the Harry Potter articles.

In [3]:
with open(('files\\Harry_Potter_Triple_Labeled'+ '.pickle'), 'rb') as file:
    triple_dicts = pickle.load(file)

In [5]:
triple_dicts[:20]

[{'subject': ('Nathan Lubbock Smith', 'NO LABEL'),
  'relation': 'is',
  'object': ('actor', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is',
  'object': ('additional position in sport of Quidditch', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is',
  'object': ('position in sport of Quidditch', 'NO LABEL')},
 {'subject': ('Captain', 'PRODUCT'),
  'relation': 'is additional position in',
  'object': ('sport of Quidditch', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is',
  'object': ('additional position in wizarding sport of Quidditch',
   'NO LABEL')},
 {'subject': ('Captain', 'PRODUCT'),
  'relation': 'is additional',
  'object': ('sport', 'NO LABEL')},
 {'subject': ('Captain', 'PRODUCT'),
  'relation': 'is additional',
  'object': ('sport', 'NO LABEL')},
 {'subject': ('Captain', 'PRODUCT'),
  'relation': 'is position in',
  'object': ('sport', 'NO LABEL')},
 {'subject': ('Captain', 'PRODUCT'),
  'relation': 'is additional position in',
  'object': ('wizarding sport of Quidditch', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is',
  'object': ('position in wizarding sport of Quidditch', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is',
  'object': ('additional position', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is position in',
  'object': ('wizarding sport', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is additional position in',
  'object': ('wizarding sport', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is',
  'object': ('position', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is additional position in',
  'object': ('wizarding sport of Quidditch', 'NO LABEL')},
 {'subject': ('Captain', 'PRODUCT'),
  'relation': 'is additional position in',
  'object': ('sport', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is position in',
  'object': ('wizarding sport of Quidditch', 'NO LABEL')},
 {'subject': ('Captain', 'PRODUCT'),
  'relation': 'is additional position in',
  'object': ('wizarding sport', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is',
  'object': ('additional position in sport', 'NO LABEL')},
 {'subject': ('Quidditch Captain', 'PERSON'),
  'relation': 'is additional position in',
  'object': ('sport of Quidditch', 'NO LABEL')}]

In [23]:
with open(('files\\label_pair_count_dict'+ '.pickle'), 'rb') as file:
    label_pair_count_dict = pickle.load(file)

In [24]:
# label_pair_count_dict

In [25]:
remove_list = []
for label_pairs in label_pair_count_dict.keys():
    if label_pairs[0] == 'NO LABEL' or label_pairs[1] == 'NO LABEL':
        remove_list.append(label_pairs)
for item in remove_list:
    del label_pair_count_dict[item]

Most frequent subject - object NER label pairs

In [27]:
pd.DataFrame({k: v for k, v in sorted(label_pair_count_dict.items(), key=lambda item: item[1], reverse=True)}.items()).head(100)

                             0      1
0             (PERSON, PERSON)  29428
1                (PERSON, ORG)  21063
2                (ORG, PERSON)  14821
3               (PERSON, DATE)  13683
4                   (ORG, ORG)  13331
5                (PERSON, GPE)   6766
6                (GPE, PERSON)   5522
7                  (ORG, DATE)   5082
8                   (GPE, ORG)   3590
9                   (ORG, GPE)   2900
10           (PERSON, PRODUCT)   2581
11                 (GPE, DATE)   2197
12             (PERSON, EVENT)   1488
13               (LOC, PERSON)   1307
14              (ORG, PRODUCT)   1303
15                  (LOC, ORG)   1270
16                  (GPE, GPE)   1267
17               (PERSON, LOC)   1251
18              (PRODUCT, ORG)    961
19               (PERSON, FAC)    793
20                (ORG, EVENT)    743
21                  (ORG, LOC)    718
22              (PERSON, NORP)    561
23       (PERSON, WORK_OF_ART)    540
24          (PERSON, CARDINAL)    533
25           (PRODUCT, PERSON)    527
26                (DATE, DATE)    507
27              (PERSON, TIME)    496
28                  (ORG, FAC)    429
29         (WORK_OF_ART, DATE)    417
30              (DATE, PERSON)    411
31             (PRODUCT, DATE)    363
32          (CARDINAL, PERSON)    360
33              (NORP, PERSON)    350
34                  (LOC, GPE)    328
35          (ORG, WORK_OF_ART)    325
36               (FAC, PERSON)    312
37                 (ORG, NORP)    287
38                 (NORP, ORG)    281
39       (WORK_OF_ART, PERSON)    278
40              (GPE, PRODUCT)    264
41            (PRODUCT, EVENT)    259
42                 (LOC, DATE)    251
43             (CARDINAL, ORG)    246
44                (GPE, EVENT)    216
45                  (LOC, FAC)    203
46                 (GPE, NORP)    200
47             (ORG, CARDINAL)    197
48          (GPE, WORK_OF_ART)    197
49                 (ORG, TIME)    183
50                  (GPE, LOC)    182
51              (PRODUCT, GPE)    156
52                 (DATE, ORG)    155
53          (WORK_OF_ART, ORG)    148
54                  (FAC, ORG)    132
55                  (FAC, GPE)    124
56            (LANGUAGE, DATE)    116
57                  (GPE, FAC)    109
58              (LOC, PRODUCT)    107
59             (ORDINAL, DATE)     93
60                 (LOC, TIME)     92
61           (PERSON, ORDINAL)     91
62            (CARDINAL, DATE)     79
63                 (DATE, LOC)     77
64  (WORK_OF_ART, WORK_OF_ART)     65
65               (EVENT, DATE)     62
66              (PRODUCT, FAC)     56
67                 (DATE, GPE)     52
68          (WORK_OF_ART, GPE)     47
69                 (GPE, TIME)     46
70                  (LOC, LOC)     45
71           (ORDINAL, PERSON)     41
72          (PERSON, LANGUAGE)     40
73             (GPE, CARDINAL)     39
74                 (FAC, DATE)     37
75                (EVENT, FAC)     37
76             (NORP, ORDINAL)     35
77                (EVENT, GPE)     35
78            (TIME, CARDINAL)     34
79              (ORG, ORDINAL)     31
80                 (NORP, GPE)     31
81              (GPE, ORDINAL)     29
82             (CARDINAL, GPE)     28
83             (LOC, CARDINAL)     27
84                (DATE, NORP)     26
85             (PRODUCT, TIME)     25
86             (ORG, QUANTITY)     24
87             (CARDINAL, FAC)     21
88                 (LOC, NORP)     20
89               (NORP, EVENT)     17
90             (EVENT, PERSON)     17
91             (ORG, LANGUAGE)     14
92        (CARDINAL, CARDINAL)     13
93             (DATE, PRODUCT)     13
94        (WORK_OF_ART, EVENT)     12
95                (EVENT, ORG)     12
96            (DATE, CARDINAL)     12
97              (ORDINAL, ORG)     11
98                (NORP, DATE)     11
99          (PERSON, QUANTITY)     10

# Exploring PERSON - PERSON Relationships

In [9]:
end = len(triple_dicts)
end

2995084

In [10]:
PER_PER_relatioships = defaultdict(int)
for i, dct in tqdm(enumerate(triple_dicts), total=end):
    if dct['subject'][1] == 'PERSON' and  dct['object'][1] == 'PERSON':
        PER_PER_relatioships[dct['relation']] += 1

  0%|          | 0/2995084 [00:00<?, ?it/s]

Most frequent relationship phrases in PERSON - PERSON relationships

In [20]:
pd.DataFrame({k: v for k, v in sorted(PER_PER_relatioships.items(), key=lambda item: item[1], reverse=True)}.items()).head(100)

                                       0    1
0                              fought in  468
1                                    met  427
2                                     in  409
3                                   told  402
4                                    was  323
5                              's son is  301
6                          was killed by  285
7                            returned to  279
8                                    has  278
9                                     at  263
10                          's family is  259
11                         was struck by  250
12                       participated in  213
13                             murdering  212
14                       biography about  195
15         fictionalised biography about  195
16  mostly fictionalised biography about  195
17                         tortured with  178
18                               capture  177
19                                seeing  175
20                                became  161
21                           was branded  156
22                                    of  155
23                             first met  147
24                         was placed by  144
25                              disliked  142
26                           tortured by  142
27                                cursed  127
28                               visited  123
29                                   had  121
30                               went on  120
31                              betrayed  119
32                                   use  118
33                               married  117
34                                  asks  115
35                                  were  112
36                             abandoned  111
37                              ' son is  111
38                                  save  110
39                       was promoted to  109
40               were also classmates of  108
41                    were classmates of  108
42                       travelling with  104
43                          protected by  104
44                                duress  102
45                           Podmore for  101
46                                inform  100
47                                  take  100
48                 later participated in   99
49                                   saw   97
50                                  kill   96
51                        also fought in   96
52                             met again   93
53                        cleaned out at   93
54                                joined   93
55                            started at   92
56                              murdered   90
57                                 asked   90
58                              lived at   87
59                              attended   87
60                                son of   86
61                    in Attenborough is   86
62                                 plays   85
63                       different times   85
64                                 times   85
65                          's sister is   85
66                               is with   83
67                                  from   83
68                                  used   79
69                             fought at   79
70                                    to   79
71                           reader like   77
72                          impersonated   77
73                            befriended   72
74                                  gave   70
75                                killed   70
76                               died of   69
77                                  left   69
78                                  tell   65
79                               grew up   64
80                                    be   63
81                                 visit   63
82                              replaced   63
83                                  took   62
84                             sister of   62
85                                taught   61
86                          started with   60
87                              enemy of   60
88                    immediate enemy of   60
89                                 is in   60
90                              Hermione   59
91                             requested   59
92                        was visited by   57
93                  was later visited by   57
94                               conjure   56
95                                framed   56
96                                  cast   56
97                                 train   55
98                    being friends with   55
99                                skills   55

In [13]:
PER_PER_names = defaultdict(int)
for i, dct in tqdm(enumerate(triple_dicts), total=end):
    if dct['subject'][1] == 'PERSON' and  dct['object'][1] == 'PERSON':
        PER_PER_names[(dct['subject'][0], dct['object'][0])] += 1

  0%|          | 0/2995084 [00:00<?, ?it/s]

Most frequent subject - object pairs in PERSON - PERSON relationships

In [19]:
pd.DataFrame({k: v for k, v in sorted(PER_PER_names.items(), key=lambda item: item[1], reverse=True)}.items()).head(100)

                                            0    1
0                            (Godric, Hollow)  750
1                               (Rita, Harry)  594
2                                (Harry, Ron)  439
3                                (Ron, Harry)  432
4                          (Pettigrew, Harry)  361
5                              (Ginny, Harry)  320
6                               (Ron, Battle)  254
7                                 (Hog, Head)  248
8                              (Dobby, Harry)  240
9                     (Minerva, Harry Potter)  222
10                            (Rowle, Battle)  198
11                                (Ron, Rose)  183
12                           (Potters, Harry)  175
13               (James Potter, Sirius Black)  171
14                           (Chaser, Seeker)  170
15               (Peter Pettigrew, Dark Mark)  156
16                            (Peter, Sirius)  156
17                             (James, Harry)  151
18                             (Harry, Harry)  149
19                           (Ron, Mundungus)  148
20                       (McGonagall, Battle)  148
21                     (Amycus, Harry Potter)  142
22               (Amycus, Minerva McGonagall)  142
23                  (Amycus, Cruciatus Curse)  142
24                             (Harry, Dobby)  142
25                                (Ron, Nick)  141
26                    (Dolohov, Harry Potter)  141
27                            (Harry, Battle)  141
28                              (Harry, Head)  139
29                            (James, Sirius)  138
30                (Harry Potter, Ron Weasley)  130
31                      (Dobby, Harry Potter)  130
32                             (Harry, James)  129
33                      (Harry, Sirius Black)  128
34                             (Fred, George)  128
35                  (Ron Weasley, Katie Bell)  127
36                      (Evan, Alastor Moody)  125
37                            (Gibbon, Curse)  125
38                    (Gibbon, Killing Curse)  125
39                            (Sirius, James)  124
40                    (Severus, James Potter)  120
41                     (Molly, Alastor Moody)  120
42                            (Dudley, Harry)  116
43                            (Hog, Head Inn)  115
44                      (Harry, Amos Diggory)  114
45                            (Vernon, Harry)  114
46                            (Harry, Burrow)  111
47                        (Harry, Head Auror)  109
48                     (Remus Lupin, Severus)  108
49                 (Peter Pettigrew, Severus)  108
50                       (Fred, Harry Potter)  107
51                  (Grindelwald, Elder Wand)  106
52           (Bertha Jorkins, Cedric Diggory)  105
53  (Captured Bertha Jorkins, Cedric Diggory)  105
54                         (Weasleys, Burrow)  104
55                 (Weasleys, Fidelius Charm)  104
56              (Hermione Granger, Pettigrew)  104
57              (Fabian Prewett, Shacklebolt)  101
58                              (Lee, Battle)  101
59                            (Ron, Scabbers)  100
60                            (Ginny, Battle)   99
61                             (Bill, Battle)   99
62                     (Bill, Fleur Delacour)   99
63                              (Ron, Sirius)   98
64                          (Macnair, Battle)   97
65                  (Minerva McGonagall, Lee)   97
66                     (James, Severus Snape)   95
67                            (Harry, Arthur)   94
68                               (Cho, Harry)   92
69                        (Harry, Tom Riddle)   90
70           (Harry Potter, Hermione Granger)   89
71                     (Fred, George Weasley)   89
72                              (Ron, Burrow)   88
73                             (Molly, Harry)   87
74                  (Prisoner, Daniel Larner)   86
75                              (Amos, Harry)   85
76                    (Harry, Joe Sowerbutts)   82
77                     (Barty, Alastor Moody)   77
78                                (Lee, Fred)   76
79             (Queenie, Gellert Grindelwald)   75
80                             (Ron, Mad Eye)   74
81                  (Harry, Hermione Granger)   74
82              (Sirius, Bellatrix Lestrange)   74
83                            (Harry, Sirius)   74
84                            (James, Chaser)   74
85           (Dark Wizard, Tom Riddle Senior)   73
86                        (Minerva, Hogwarts)   73
87                            (Harry, Cedric)   72
88                        (Ron, Harry Potter)   71
89                          (Harry, Hogwarts)   70
90                            (Pierre, Peter)   70
91                      (Diggory, Dragon Pox)   69
92                               (Ron, Dobby)   69
93                              (Lily, Harry)   69
94                    (Daniel Radcliffe, Ron)   68
95                (Ginny Weasley, Tom Riddle)   68
96                              (Ron, Keeper)   68
97                   (Weasleys, Harry Potter)   67
98                          (James, Hogwarts)   66
99                              (Percy, Head)   64

In [17]:
married_df = pd.DataFrame(columns = ['subject', 'married', 'object'])
for i, dct in tqdm(enumerate(triple_dicts), total=end):
    if dct['relation'] == 'married':
        df = {'subject': dct['subject'][0], 'married': dct['relation'], 'object': dct['object'][0]}
        married_df = married_df.append(df, ignore_index = True)

  0%|          | 0/2995084 [00:00<?, ?it/s]

In [18]:
married_df.head(100)

,subject,married,object
0,Ron,married,Hermione
1,Ron,married,Hermione
2,She,married,Harry Potter
3,he,married,Ginny
4,he,married,Ginny
5,Bill,married,Fleur Delacour
6,She,married,Ron Weasley
7,Ron,married,Hermione
8,Ron,married,Hermione
9,Ron,married,Hermione
10,Ron,married,Hermione
11,Narcissa,married,blood wizards
12,Bellatrix,married,blood wizards
13,Narcissa,married,pure blood wizards
14,Bellatrix,married,pure blood wizards
15,Andromeda,married,Muggle born Ted Tonks
16,Andromeda,married,born Ted Tonks
17,Andromeda,married,Ted Tonks
18,She,married,they would work
19,notion,married,Muggle born wizard
20,notion,married,born wizard
21,notion,married,wizard
22,Ron,married,Hermione
23,Ron,married,Hermione
24,She,married,Ron Weasley
25,she,married,James Potter
26,she,married,George Weasley
27,Cho,married,Muggle
28,Cho,married,Muggle individual
29,she,married,Muggle
30,he,married,his former classmate
31,Ron,married,Padma Patil
32,Ron,married,Padma Patil
33,She,married,Harry Potter
34,his sister,married,Arthur Weasley
35,Monsieur Delacour,married,half Veela witch Apolline Delacour
36,George,married,Angelina Johnson
37,she,married,a
38,Nymphadora,married,Remus Lupin
39,she,married,while her sisters married into respectable blo...
40,she,married,while her sisters married
41,she,married,her sisters married into respectable pure bloo...
42,she,married,while her sisters married into blood families
43,she,married,her sisters married into pure blood families
44,she,married,her sisters married into blood families
45,she,married,her sisters married
46,she,married,while her sisters married into respectable pur...
47,she,married,while her sisters married into pure blood fami...
48,she,married,her sisters married into respectable blood fam...
49,she,married,a
50,Hermione,married,Ron Weasley
51,Hermione,married,Ronald Weasley
52,Ted,married,Andromeda
53,Ted,married,Andromeda Black
54,his son,married,Ted 's daughter
55,his son,married,Nymphadora
56,he,married,witch
57,he,married,Muggle born witch
58,he,married,born witch
59,Rionach 's sister,married,Muggle friend of nearby Pocumtuc Native tribe
60,Rionach 's sister,married,Muggle friend of nearby Pocumtuc Native Americ...
61,Rionach 's sister,married,Muggle friend of nearby Pocumtuc American tribe
62,Rionach 's sister,married,Muggle friend of Pocumtuc American tribe
63,Rionach 's sister,married,Muggle friend of Pocumtuc Native American tribe
64,Rionach 's sister,married,Muggle friend
65,Rionach 's sister,married,Muggle friend of Pocumtuc tribe
66,Rionach 's sister,married,Muggle friend of nearby Pocumtuc tribe
67,Rionach 's sister,married,Muggle friend of Pocumtuc Native tribe
68,she,married,James Potter
69,Rose,married,Lucius 's grandson
70,Rose,married,Lucius 's grandson
71,Rose,married,Lucius 's grandson
72,Ron,married,Hermione
73,Ron,married,Hermione
74,Ron,married,Hermione
75,Ron,married,Hermione
76,Ron,married,Hermione
77,Ron,married,Hermione
78,she,married,James Potter
79,Rionach 's sister,married,Muggle friend of nearby Pocumtuc Native tribe
80,Rionach 's sister,married,Muggle friend of nearby Pocumtuc Native Americ...
81,Rionach 's sister,married,Muggle friend of nearby Pocumtuc American tribe
82,Rionach 's sister,married,Muggle friend of Pocumtuc Native American tribe
83,Rionach 's sister,married,Muggle friend of Pocumtuc American tribe
84,Rionach 's sister,married,Muggle friend
85,Rionach 's sister,married,Muggle friend of Pocumtuc tribe
86,Rionach 's sister,married,Muggle friend of nearby Pocumtuc tribe
87,Rionach 's sister,married,Muggle friend of Pocumtuc Native tribe
88,She,married,Ron Weasley
89,he,married,witch
90,He,married,Merope Gaunt
91,Tonks,married,Remus Lupin
92,Rionach 's sister,married,Muggle friend of nearby Pocumtuc Native tribe
93,Rionach 's sister,married,Muggle friend of nearby Pocumtuc Native Americ...
94,Rionach 's sister,married,Muggle friend of nearby Pocumtuc American tribe
95,Rionach 's sister,married,Muggle friend of Pocumtuc Native American tribe
96,Rionach 's sister,married,Muggle friend of Pocumtuc American tribe
97,Rionach 's sister,married,Muggle friend
98,Rionach 's sister,married,Muggle friend of Pocumtuc tribe
99,Rionach 's sister,married,Muggle friend of nearby Pocumtuc tribe